### PR TITLE
fix: broken links

### PR DESCRIPTION
**Pull request by sashasushko**
I [added the Linkinator](https://github.com/neondatabase/website/actions/workflows/linkinator.yml) – it's a tool which helps detect broken links. The check is every Monday.

This PR is an example of fixing content [by the last Linkinator's report](https://github.com/neondatabase/website/actions/runs/3671442386).

### CODE REVIEW

**Comment by sashasushko** [comment]
In addition, there are hidden `<a>`-tags with broken `href` attribute in the blog.

```text
https://neon.tech/blog/paxos/
  [404] https://neon.tech/static/19e9406cf8c0d568f3d3cf8078b7333b/08123/diagram-1.jpg
  [404] https://neon.tech/static/10932a0e3cc4304daa8ea15182a09337/086dd/neon-consensus-algorithm-2.jpg
  [404] https://neon.tech/static/cc31887ac41482ad199e936dc21c42a2/08123/diagram-2.jpg
  [404] https://neon.tech/static/75e80c6fcb30fd0e8d2d87cc8d97b55a/08123/diagram-3.jpg
 
https://neon.tech/blog/architecture-decisions-in-neon/
  [404] https://neon.tech/static/8bf9c44a9c2d6ddd0e4bde50e1e262ab/2b73a/neon-architecture-2.png
```

I'm not sure for what reasons these links were place there. But I removed one...

Снимок экрана 2022-12-13 в 09 15 52

...and the problem was gone, but the blog post still looks like before – https://neon.tech/blog/hello-world/

----

Also, there are non-fixable (from our side) items in report:

```text
https://neon.tech/blog/serverless-driver-for-postgres/
  [403] https://blog.cloudflare.com/neon-postgres-database-from-workers/
  [403] https://blog.cloudflare.com/tls-1-3-overview-and-q-and-a/
```

_We can't fix `cloudflare.com` url :-) only skip it_

```text
https://neon.tech/docs/manage/api-keys/
  [404] https://console.neon.tech/api/v1
```

_`console.neon.tech` also not available for us_

**Review by danieltprice — APPROVED** [review]
lgtm!

**Comment by sashasushko** [comment]
> The links from the blog post appear to work when clicked from the blog post. Is there an issue with the way they are defined?

Yep. Right now, these links not wrapped the image. They just were placed before or after image.

Снимок экрана 2022-12-14 в 19 22 08

Someone, who writes content for the blog, should know how to fix it (I guess). Let's move this discussion to Slack, if you don't mind.

**Comment by bolotskydev** [comment]
@sashasushko @danieltprice I don't think these ghostlike links have been put there intentionally. Let me clear the blog out and let's move on, I'll keep an eye on this for some time to get the idea how it happened so

**Review by bolotskydev — APPROVED** [review]

**Pull request merged**
