### PR TITLE
Create 2023-02-06.md

### PR DESCRIPTION
**Pull request by duskpoet**
Preview:
https://neon-next-git-rc-eduard-2023-02-06-neondatabase.vercel.app/docs/release-notes

### CODE REVIEW

**Comment by danieltprice** [comment]
Removed the email validation item since this seems to apply to internal user emails only: https://github.com/neondatabase/cloud/issues/3772

**Comment by duskpoet** [comment]
> Removed the email validation item since this seems to apply to internal user emails only: [neondatabase/cloud#3772](https://github.com/neondatabase/cloud/issues/3772)

I think this change relates to all created users, @Daniel-ef ?

**Comment by danieltprice** [comment]
Thank you. I will add it back!

**Review by danieltprice — APPROVED** [review]
lgtm

**Pull request merged**
