### PR TITLE
feat: add doc about old clients compatibility

### PR DESCRIPTION
**Pull request by kelvich**

### CODE REVIEW

**Comment by kelvich** [comment]
@stepashka, who would be an appropriate reviewer here?

**Review by stepashka — APPROVED** [review]
Approving to expedite the shipping of this.

**Comment by stepashka** [comment]
@WeaponXII , even though this is approved, feel free to make your suggestions and submit the feedback (e.g. in a new GH issue), if you have time to look at this.

**Comment by WeaponXII** [comment]
Will do, I'll add it to my list @stepashka

**Pull request merged**
