### PR TITLE
pricing page update

### PR DESCRIPTION
**Pull request by americano98**
This pull request brings update for pricing page.

TODO:

- [x] check actual links
- [x] check GA events

Steps to check:

- open [preview](https://neon-next-git-upd-pricing-page-neondatabase.vercel.app/pricing)
- make sure that everything looks and feels as expected

### CODE REVIEW

**Comment by acervantes23** [comment]
Some comments:

- remove Customer Extensions from the free plan
- change `Read Replicas` to `Instant Read Replicas`
- add `Custom SLAs` to the Enterprise plan (unless their is strong objection)

I think Proposales should replace ketteQ and that should be marked as a `Launch` customer. With something like:  Proposales streamlines their development & Testing with Neon

replaced Proposales with Profitflow and have some copy like: `75% cost reduction by moving a fleet of databases powering multi-tenant SaaS to Neon.`


I personally don't like that in the plans the `From` in `From $/ month` is so big. I think it would be nicer to reduce the font size so the emphasis is more on the fixed amount vs. highlighting variability.

**Comment by acervantes23** [comment]
Also, it's not very nice that the space between the quotes and `Detailed plan comparison` shrinks when you get to the quote from Lincon

**Comment by acervantes23** [comment]
Instead of mentioning CUs on the would it make more sense to say the exact resources? I'm just thinking about first impressions and most users looking at this for the first time might not automatically know what a CU is. CPU/ RAM helps with readibility.

**Comment by acervantes23** [comment]
In the hover should we say `CU-hrs compute` is confusing. Also we should say /mo so that its clear the usage is monthly (feel free to disagree/provide counter point)

Screen Shot 2024-02-13 at 10 23 05 PM

**Comment by acervantes23** [comment]
Instead of `Neon brings serverless architecture to PostgreSQL, which allows us to offer you flexible usage and volume-based plans.` can we have something that resonate more with the buying decision? 

E.g. Supabase has `Start building for free, collaborate with a team, then scale to millions of users.`

**Comment by acervantes23** [comment]
We need to add more customer logos. Let's get rid of the ones that don't give us anything since no one has heard of them:

The Fabric.io
Octolis
WunderGraph
Airplane (they got bought)
Dynaboard (they are winding down)
bunnyshell
illa
FL0

And replace them with:

Zimmer Biomet
10x Genomics
OUTFRONT Media
Masterschool
Code Institute
Branch Financial
Supergood.ai
EQT

**Comment by ruf-io** [comment]
@americano98 @k8isdead round of dev requests for you:

- [ ] Fix the jumping caused by quotes of different heights https://github.com/neondatabase/website/assets/11527560/661d6e29-44e5-49d8-befc-2f795b2675de
- [ ] Swap the scrolling logos for the ones that @acervantes23 has mentioned: Zimmer Biomet, 10x Genomics, OUTFRONT Media, Masterschool, Code Institute, Branch Financial, Supergood.ai, EQT
- [ ] Fix placement of a "From" prefix on Launch and Scale hero 
image
- [ ] Check that tooltips I added are done properly and add some visual indicator 
image

**Review by acervantes23 — APPROVED** [review]

**Comment by acervantes23** [comment]
@ruf-io I think we should take out "Serverless" and instead just have "Goodbye Infrastructure, Hello Postgres".

**Comment by ruf-io** [comment]
@k8isdead We've removed tooltips so that task is no longer needed

**Comment by acervantes23** [comment]
I'm a slow reader so take this with a grain of salt but It feels to me like the quotes rotate to quickly.

Screen Shot 2024-02-15 at 9 26 08 PM

**Comment by acervantes23** [comment]
@k8isdead let's also update the FAQ with the following:

- **When will I be billed?**
    
    Neon bills for the past month's usage at the beginning of each calendar month. For more information, see [[Manage billing](https://neon-next-git-upd-pricing-page-neondatabase.vercel.app/docs/introduction/manage-billing)](https://neon-next-git-upd-pricing-page-neondatabase.vercel.app/docs/introduction/manage-billing).
    
- **What happens if I cancel my subscription?**
    
    If you cancel your subscription you will be be required to downgrade your account to the free limits.
    
- **Do I get a notification if I am approaching my usage limits?**
    
    Yes, we display your usage consumption in the Neon admin console and will email you when you are within 20% of your included usage.
    
- **Why are we limited to 500 branches per project?**
    
    Neon implements usage limits for branching in order to prevent potential abuse of the service which can negatively impact other users. For customers seeking higher limits please contact customer-success@neon.tech.
    
- **Does Neon charge for storage in database branches?**
    
    Neon charges for unique storage. Data that a branch shares in common with a parent branch is not considered unique, but data changes to a branch are counted toward storage.
    
    [[Read more](https://neon-next-git-upd-pricing-page-neondatabase.vercel.app/docs/introduction/billing#project-storage)](https://neon-next-git-upd-pricing-page-neondatabase.vercel.app/docs/introduction/billing#project-storage).
    
- **What happens when I exceed 10 GiB storage on the Launch plan?**
    
    If you exceed your storage quota on the Launch plan, the Neon team will collaborate with you to address your storage needs. This may involve providing guidance on optimizing storage usage or exploring alternative plans that better suit your requirements. It's important to note that Neon does not automatically halt write operations when you surpass your limits. You can send related inquiries to customer-success@neon.tech.

**Review by acervantes23 — APPROVED** [review]

**Review by acervantes23 — APPROVED** [review]

**Review by acervantes23 — APPROVED** [review]

**Review by acervantes23 — APPROVED** [review]

**Pull request merged**
