### PR TITLE
Add release notes

### PR DESCRIPTION
**Pull request by klink**

### CODE REVIEW

**Comment by alexandriastech** [comment]
@klink Thank you for creating the Release Notes page, will get back to you later today on this!

**Review by alexandriastech — COMMENTED** [review]
Hi @klink,

Thanks for making the release notes section.

I recommend making the release notes a single page and changing the page title also to "Release Notes". Release Notes can also be at the bottom of the sidebar since information placement is important and often based on priority determined by the user.


Each date can have a heading on that same page with the following information regarding any updates made under it. Something like this: 

# Release Notes

## 2022-06-27 

### What's New?

### Bug Fixes

**Comment by pkafei** [comment]
@klink 

@alexandriastech left some comments and suggestions above. Let us know if you need more details or clarification.

**Review by stepashka — APPROVED** [review]

**Comment by stepashka** [comment]
the next step is to source the release notes from the team :)

**Comment by ololobus** [comment]
@klink @stepashka pushed a proposal for the two recent releases

**Review by stepashka — APPROVED** [review]

**Pull request merged**
