### PR TITLE
Amalogmation of some potential improvements

### PR DESCRIPTION
**Pull request by tristan957**

### CODE REVIEW

**Comment by tristan957** [comment]
Tedious work!

**Comment by tristan957** [comment]
I didn't notice any changes with the `http` language change, but that seems fine.

Aside, but the syntax highlighting we have for JSON could use some improvements. Way too much of the same green. Any way to use a lighter green for either keys or values?

**Review by danieltprice — APPROVED** [review]

**Comment by danieltprice** [comment]
Thank you @tristan957 !

**Comment by tristan957** [comment]
Happy to help :). Does it matter if you or I merge the PR? First contribution in this repo.

**Pull request merged**
