### PR TITLE
Update query-postgres-azure-functions.md

### PR DESCRIPTION
**Pull request by AdalbertPungu**
Preview:
https://neon-next-git-fork-adalbertpungu-update-ap-neondatabase.vercel.app/guides/query-postgres-azure-functions

### CODE REVIEW

**Comment by danieltprice** [comment]
Hi @AdalbertPungu 

Thank you for the update. The indentation is a bit off here . The content should align under the step.
For example, the indentation is incorrect here. 
image

There are a few instances of this in the doc. Can you fix those?

Thank you!

**Comment by AdalbertPungu** [comment]
> Hi @AdalbertPungu
> 
> Thank you for the update. The indentation is a bit off here . The content should align under the step. For example, the indentation is incorrect here. image
> 
> There are a few instances of this in the doc. Can you fix those?
> 
> Thank you!

I have just corrected

**Review by danieltprice — APPROVED** [review]

**Comment by sam-harri** [comment]
There are SSL issues:
`Error fetching clients: error: connection is insecure (try using `sslmode=require`)`

Change the client creation to include the SSL flag
```javascript
const client = new Client({
  user: process.env.DB_USER,
  host: process.env.DB_HOST,
  database: process.env.DB_NAME,
  password: process.env.DB_PASSWORD,
  ssl: true,
});
```

**Comment by AdalbertPungu** [comment]
> There are SSL issues: `Error fetching clients: error: connection is insecure (try using 'sslmode=require')`
> 
> Change the client creation to include the SSL flag
> 
> ```js
> const client = new Client({
>   user: process.env.DB_USER,
>   host: process.env.DB_HOST,
>   database: process.env.DB_NAME,
>   password: process.env.DB_PASSWORD,
>   ssl: true,
> });
> ```

Here is the PR https://github.com/neondatabase/website/pull/2413 update

**Pull request merged**
