### PR TITLE
Dprice partner integration doc

### PR DESCRIPTION
**Pull request by danieltprice**
This is an initial draft of a partner integration document. It has not been validated.

### CODE REVIEW

**Comment by antonyc** [comment]
Is this expected to be accessible by users publicly?

**Comment by raoufchebri** [comment]
it seems we're early for this to be published

**Comment by danieltprice** [comment]
Closing this pull request. Instructions can be generated from the cloud repo guide.

**Comment by acervantes23** [comment]
Thanks Daniel! I think we should return to this after "GA" (I know we changed the name) since we have more urgent matters to attend to. @stepashka what do you think?

**Pull request closed without merging**
