### PR TITLE
Create nestjs.md

### PR DESCRIPTION
**Pull request by danieltprice**
initial content

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
@danieltprice 

I do have a task on my hand at https://github.com/orgs/neondatabase/projects/81/views/1?pane=issue&itemId=65883291, will get this done by next week I think.

**Comment by rishi-raj-jain** [comment]
nice that you have thought of it already!

**Comment by rishi-raj-jain** [comment]
@danieltprice 

We have this now: https://github.com/neondatabase/examples/tree/main/with-nestjs.

**Comment by danieltprice** [comment]
We've added via another PR. Closing.

**Pull request closed without merging**
