### PR TITLE
guide: Real-Time Notifications using pg_notify with Neon Postgres

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
Preview: https://neon-next-git-pg-notify-neon-neondatabase.vercel.app/guides/pg-notify

### CODE REVIEW

**Comment by danieltprice** [comment]
Neon supports triggers for DML operations, but not event triggers for DDL events (the latter requires superuser). I've changed "event trigger" to just "trigger:

Also, please note that due to autosuspend, session contexts like notifications are lost when a compute suspends. Consider adding a note/warning to this effect if applicable here, which I think it might be. See:
https://neon.tech/docs/reference/compatibility#session-context

**Review by danieltprice — APPROVED** [review]
Please look at session context issue. May require a note/warning.

**Comment by rishi-raj-jain** [comment]
> Neon supports triggers for DML operations, but not event triggers for DDL events (the latter requires superuser). I've changed "event trigger" to just "trigger:

Thank you!

**Comment by rishi-raj-jain** [comment]
> Also, please note that due to autosuspend, session contexts like notifications are lost when a compute suspends. Consider adding a note/warning to this effect if applicable here, which I think it might be. See:

Oh yes! You're 100% correct. On it.

**Review by danieltprice — APPROVED** [review]

**Pull request merged**
